FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install --production

COPY server/ ./server/
COPY index.html ./
COPY *.html ./
COPY *.tsx ./
COPY react-global.js ./

ENV PORT=8080

EXPOSE 8080

CMD ["node", "server/server.js"]
